/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tricky;

/**
 *
 * @author Estudiantes
 */
public class Grafica extends javax.swing.JFrame {

    /**
     * Creates new form Grafica
     */
    
    Jugador jugadorGrafico = new Jugador();
    Tablero tableroGrafico = new Tablero();
    
    int valor;
    boolean juego;
    boolean triqui;
    boolean resultado;
    int posI;
    int posJ;
    
    public Grafica() {
        initComponents();
        this.juego = true;
        this.triqui = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casilla00 = new javax.swing.JButton();
        casilla01 = new javax.swing.JButton();
        casilla02 = new javax.swing.JButton();
        casilla10 = new javax.swing.JButton();
        casilla20 = new javax.swing.JButton();
        casilla11 = new javax.swing.JButton();
        casilla12 = new javax.swing.JButton();
        casilla21 = new javax.swing.JButton();
        casilla22 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        casilla00.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        casilla00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla00MouseClicked(evt);
            }
        });

        casilla01.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        casilla01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla01MouseClicked(evt);
            }
        });

        casilla02.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        casilla02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla02MouseClicked(evt);
            }
        });

        casilla10.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        casilla10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla10MouseClicked(evt);
            }
        });

        casilla20.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        casilla20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla20MouseClicked(evt);
            }
        });

        casilla11.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        casilla11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla11MouseClicked(evt);
            }
        });

        casilla12.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        casilla12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla12MouseClicked(evt);
            }
        });

        casilla21.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        casilla21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla21MouseClicked(evt);
            }
        });

        casilla22.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        casilla22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casilla22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(casilla20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla00, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(casilla01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla21, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(casilla02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla22, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(casilla02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla00, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(casilla11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(casilla20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casilla22, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casilla00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla00MouseClicked
        // TODO add your handling code here:
        valor = jugadorGrafico.marcar();
        posI = 0;
        posJ = 0;
                
        switch(valor){
            case 0:
                casilla00.setText("O");
                break;
            case 1:
                casilla00.setText("X");
                break;
            case 2:
                this.juego = false;
                break;
        }
        casilla00.setEnabled(false);
        
        triqui = tableroGrafico.analizar(posI, posJ, valor);
    }//GEN-LAST:event_casilla00MouseClicked

    private void casilla01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla01MouseClicked
        // TODO add your handling code here:
        valor = jugadorGrafico.marcar();
        posI = 0;
        posJ = 1;
        
        switch(valor){
            case 0:
                casilla01.setText("O");
                break;
            case 1:
                casilla01.setText("X");
                break;
            case 2:
                this.juego = false;
        }
        casilla01.setEnabled(false);
        
        triqui = tableroGrafico.analizar(posI, posJ, valor);
    }//GEN-LAST:event_casilla01MouseClicked

    private void casilla02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla02MouseClicked
        // TODO add your handling code here:
        valor = jugadorGrafico.marcar();
        posI = 0;
        posJ = 2;
        
        switch(valor){
            case 0:
                casilla02.setText("O");
                break;
            case 1:
                casilla02.setText("X");
                break;
            case 2:
                this.juego = false;
        }
        casilla02.setEnabled(false);
        
        triqui = tableroGrafico.analizar(posI, posJ, valor);
    }//GEN-LAST:event_casilla02MouseClicked

    private void casilla10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla10MouseClicked
        // TODO add your handling code here:
        valor = jugadorGrafico.marcar();
        posI = 1;
        posJ = 0;
        
        switch(valor){
            case 0:
                casilla10.setText("O");
                break;
            case 1:
                casilla10.setText("X");
                break;
            case 2:
                this.juego = false;
        }
        casilla10.setEnabled(false);
        
        triqui = tableroGrafico.analizar(posI, posJ, valor);
    }//GEN-LAST:event_casilla10MouseClicked

    private void casilla11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla11MouseClicked
        // TODO add your handling code here:
        valor = jugadorGrafico.marcar();
        posI = 1;
        posJ = 1;
        
        switch(valor){
            case 0:
                casilla11.setText("O");
                break;
            case 1:
                casilla11.setText("X");
                break;
            case 2:
                this.juego = false;
        }
        casilla11.setEnabled(false);
        
        triqui = tableroGrafico.analizar(posI, posJ, valor);
    }//GEN-LAST:event_casilla11MouseClicked

    private void casilla12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla12MouseClicked
        // TODO add your handling code here:
        valor = jugadorGrafico.marcar();
        posI = 1;
        posJ = 2;
        
        switch(valor){
            case 0:
                casilla12.setText("O");
                break;
            case 1:
                casilla12.setText("X");
                break;
            case 2:
                this.juego = false;
        }
        casilla12.setEnabled(false);
        
        triqui = tableroGrafico.analizar(posI, posJ, valor);
    }//GEN-LAST:event_casilla12MouseClicked

    private void casilla20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla20MouseClicked
        // TODO add your handling code here:
        valor = jugadorGrafico.marcar();
        posI = 2;
        posJ = 0;
        
        switch(valor){
            case 0:
                casilla20.setText("O");
                break;
            case 1:
                casilla20.setText("X");
                break;
            case 2:
                this.juego = false;
        }
        casilla20.setEnabled(false);
        
        triqui = tableroGrafico.analizar(posI, posJ, valor);
    }//GEN-LAST:event_casilla20MouseClicked

    private void casilla21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla21MouseClicked
        // TODO add your handling code here:
        valor = jugadorGrafico.marcar();
        posI = 2;
        posJ = 1;
        
        switch(valor){
            case 0:
                casilla21.setText("O");
                break;
            case 1:
                casilla21.setText("X");
                break;
            case 2:
                this.juego = false;
        }
        casilla21.setEnabled(false);
        
        triqui = tableroGrafico.analizar(posI, posJ, valor);
    }//GEN-LAST:event_casilla21MouseClicked

    private void casilla22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casilla22MouseClicked
        // TODO add your handling code here:
        valor = jugadorGrafico.marcar();
        posI = 2;
        posJ = 2;
        
        switch(valor){
            case 0:
                casilla22.setText("O");
                break;
            case 1:
                casilla22.setText("X");
                break;
            case 2:
                this.juego = false;
        }
        casilla22.setEnabled(false);
        
        triqui = tableroGrafico.analizar(posI, posJ, valor);
    }//GEN-LAST:event_casilla22MouseClicked

    /**
     * @param args the command line arguments
     */
    boolean resultado(){
        if(triqui && juego){
            resultado = true;
        }
        if (triqui==false && juego==false){
            resultado = false;
        }else{
            if (triqui && juego==false){
                resultado = true;
            }
        }
        return resultado;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton casilla00;
    private javax.swing.JButton casilla01;
    private javax.swing.JButton casilla02;
    private javax.swing.JButton casilla10;
    private javax.swing.JButton casilla11;
    private javax.swing.JButton casilla12;
    private javax.swing.JButton casilla20;
    private javax.swing.JButton casilla21;
    private javax.swing.JButton casilla22;
    // End of variables declaration//GEN-END:variables
}
